<a href="https://colab.research.google.com/github/PierDiella/BigData_Rep/blob/main/BaseDati_ProjectPOLIBA_RegressioneMultipla.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import normalize
import math, copy
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler

In [4]:
df=pd.read_csv("student_prediction.csv")

df.head(10)

STUDENTID  AGE  GENDER  HS_TYPE  SCHOLARSHIP  WORK  ACTIVITY  PARTNER  \
0   STUDENT1    2       2        3            3     1         2        2   
1   STUDENT2    2       2        3            3     1         2        2   
2   STUDENT3    2       2        2            3     2         2        2   
3   STUDENT4    1       1        1            3     1         2        1   
4   STUDENT5    2       2        1            3     2         2        1   
5   STUDENT6    2       2        2            3     2         2        2   
6   STUDENT7    1       2        2            4     2         2        2   
7   STUDENT8    1       1        2            3     1         1        1   
8   STUDENT9    2       1        3            3     2         1        1   
9  STUDENT10    2       1        2            3     2         2        1   

   SALARY  TRANSPORT  ...  PREP_STUDY  PREP_EXAM  NOTES  LISTENS  \
0       1          1  ...           1          1      3        2   
1       1          1  ...           1          1      3        2   
2       2          4  ...           1          1      2        2   
3       2          1  ...           1          2      3        2   
4       3          1  ...           2          1      2        2   
5       2          1  ...           1          1      1        2   
6       1          1  ...           1          1      3        3   
7       2          2  ...           3          1      3        2   
8       1          1  ...           1          1      3        2   
9       3          4  ...           1          1      2        2   

   LIKES_DISCUSS  CLASSROOM  CUML_GPA  EXP_GPA  COURSE ID  GRADE  
0              1          2         1        1          1      1  
1              3          2         2        3          1      1  
2              1          1         2        2          1      1  
3              2          1         3        2          1      1  
4              2          1         2        2          1      1  
5              1          2         4        4          1      2  
6              3          3         4        4          1      5  
7              2          1         1        1          1      2  
8              2          2         4        3          1      5  
9              2          2         1        2          1      0  

[10 rows x 33 columns]

In [5]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145 entries, 0 to 144
Data columns (total 33 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   STUDENTID      145 non-null    object
 1   AGE            145 non-null    int64 
 2   GENDER         145 non-null    int64 
 3   HS_TYPE        145 non-null    int64 
 4   SCHOLARSHIP    145 non-null    int64 
 5   WORK           145 non-null    int64 
 6   ACTIVITY       145 non-null    int64 
 7   PARTNER        145 non-null    int64 
 8   SALARY         145 non-null    int64 
 9   TRANSPORT      145 non-null    int64 
 10  LIVING         145 non-null    int64 
 11  MOTHER_EDU     145 non-null    int64 
 12  FATHER_EDU     145 non-null    int64 
 13  #_SIBLINGS     145 non-null    int64 
 14  KIDS           145 non-null    int64 
 15  MOTHER_JOB     145 non-null    int64 
 16  FATHER_JOB     145 non-null    int64 
 17  STUDY_HRS      145 non-null    int64 
 18  READ_FREQ      145 non-null   

In [6]:
X1 = df[['AGE', 'GENDER', 'HS_TYPE', 'SCHOLARSHIP', 'WORK', 'ACTIVITY', 'PARTNER', 'SALARY', 'TRANSPORT', 'LIVING', 'MOTHER_EDU', 'FATHER_EDU', '#_SIBLINGS', 'KIDS', 'MOTHER_JOB', 'FATHER_JOB', 'STUDY_HRS', 'READ_FREQ', 'READ_FREQ_SCI', 'ATTEND_DEPT', 'IMPACT', 'ATTEND', 'PREP_STUDY', 'PREP_EXAM', 'NOTES', 'LISTENS', 'LIKES_DISCUSS', 'CLASSROOM', 'CUML_GPA', 'EXP_GPA']].to_numpy()                 #converte dataframe in array
Y1 = df[['GRADE']].to_numpy()

X2 = np.array(X1, dtype=float)                                                       #converte i valori della variabile in float64
                                                                #scambia le righe con le colonne di un array, sicuramente funziona sia con matrici che con vettori
Y2 = np.array(Y1, dtype=float)



print(X2)



print(Y2)



[[2. 2. 3. ... 2. 1. 1.]
 [2. 2. 3. ... 2. 2. 3.]
 [2. 2. 2. ... 1. 2. 2.]
 ...
 [1. 1. 1. ... 1. 4. 3.]
 [2. 1. 2. ... 1. 5. 3.]
 [1. 1. 1. ... 1. 5. 4.]]
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [2.]
 [5.]
 [2.]
 [5.]
 [0.]
 [2.]
 [0.]
 [0.]
 [1.]
 [2.]
 [2.]
 [1.]
 [2.]
 [2.]
 [3.]
 [1.]
 [1.]
 [3.]
 [1.]
 [2.]
 [3.]
 [1.]
 [1.]
 [3.]
 [5.]
 [5.]
 [3.]
 [1.]
 [2.]
 [2.]
 [1.]
 [2.]
 [1.]
 [2.]
 [1.]
 [1.]
 [1.]
 [1.]
 [4.]
 [1.]
 [3.]
 [5.]
 [3.]
 [1.]
 [2.]
 [1.]
 [4.]
 [1.]
 [5.]
 [3.]
 [3.]
 [5.]
 [4.]
 [3.]
 [5.]
 [2.]
 [5.]
 [3.]
 [5.]
 [3.]
 [2.]
 [5.]
 [1.]
 [5.]
 [5.]
 [7.]
 [6.]
 [6.]
 [6.]
 [7.]
 [7.]
 [4.]
 [7.]
 [4.]
 [3.]
 [4.]
 [3.]
 [7.]
 [7.]
 [7.]
 [4.]
 [5.]
 [6.]
 [6.]
 [6.]
 [6.]
 [6.]
 [7.]
 [4.]
 [6.]
 [5.]
 [7.]
 [6.]
 [7.]
 [7.]
 [6.]
 [7.]
 [7.]
 [7.]
 [3.]
 [7.]
 [7.]
 [6.]
 [6.]
 [7.]
 [2.]
 [2.]
 [2.]
 [1.]
 [2.]
 [1.]
 [1.]
 [1.]
 [1.]
 [2.]
 [1.]
 [0.]
 [2.]
 [1.]
 [3.]
 [2.]
 [3.]
 [1.]
 [0.]
 [3.]
 [1.]
 [4.]
 [3.]
 [3.]
 [1.]
 [2.]
 [0.]
 [2.]
 [0.]
 [0.]
 [5.

Squared normalization

In [11]:
X = normalize(X2, norm='l2')

Y=Y2
print(X)

[[0.1796053  0.1796053  0.26940795 ... 0.1796053  0.08980265 0.08980265]
 [0.18490007 0.18490007 0.2773501  ... 0.18490007 0.18490007 0.2773501 ]
 [0.1933473  0.1933473  0.1933473  ... 0.09667365 0.1933473  0.1933473 ]
 ...
 [0.07881104 0.07881104 0.07881104 ... 0.07881104 0.31524416 0.23643312]
 [0.14948702 0.07474351 0.14948702 ... 0.07474351 0.37371755 0.22423053]
 [0.07254763 0.07254763 0.07254763 ... 0.07254763 0.36273813 0.2901905 ]]


MinMaxRegularization

In [ ]:
scaler = MinMaxScaler(feature_range=(0, 10))                                      # regularization

X = scaler.fit_transform(X2)



scaler = MinMaxScaler(feature_range=(0, 30))

Y = scaler.fit_transform(Y2)

print(X)
print(Y)

[[ 5.         10.         10.         ...  5.          0.
   0.        ]
 [ 5.         10.         10.         ...  5.          2.5
   6.66666667]
 [ 5.         10.          5.         ...  0.          2.5
   3.33333333]
 ...
 [ 0.          0.          0.         ...  0.          7.5
   6.66666667]
 [ 5.          0.          5.         ...  0.         10.
   6.66666667]
 [ 0.          0.          0.         ...  0.         10.
  10.        ]]
[[ 4.28571429]
 [ 4.28571429]
 [ 4.28571429]
 [ 4.28571429]
 [ 4.28571429]
 [ 8.57142857]
 [21.42857143]
 [ 8.57142857]
 [21.42857143]
 [ 0.        ]
 [ 8.57142857]
 [ 0.        ]
 [ 0.        ]
 [ 4.28571429]
 [ 8.57142857]
 [ 8.57142857]
 [ 4.28571429]
 [ 8.57142857]
 [ 8.57142857]
 [12.85714286]
 [ 4.28571429]
 [ 4.28571429]
 [12.85714286]
 [ 4.28571429]
 [ 8.57142857]
 [12.85714286]
 [ 4.28571429]
 [ 4.28571429]
 [12.85714286]
 [21.42857143]
 [21.42857143]
 [12.85714286]
 [ 4.28571429]
 [ 8.57142857]
 [ 8.57142857]
 [ 4.28571429]
 [ 8.57142857

In [12]:
print(X.shape)
print(Y.shape)

(145, 30)
(145, 1)


https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html


La funzione train_test_split di scikit-learn è utilizzata per dividere un dataset in due sottoinsiemi casuali di addestramento e test. I parametri della funzione sono i seguenti:

arrays: una sequenza di oggetti con la stessa lunghezza o forma. Gli input ammessi sono liste, array NumPy, matrici sparse SciPy o DataFrame pandas.
test_size: la proporzione del dataset da includere nel sottoinsieme di test. Se è un intero, rappresenta il numero assoluto di campioni di test. Se è None, il valore viene impostato sul complemento della dimensione del set di addestramento. Se train_size è anche None, viene impostato su 0,25.
train_size: la proporzione del dataset da includere nel sottoinsieme di addestramento. Se è un intero, rappresenta il numero assoluto di campioni di addestramento. Se è None, il valore viene impostato automaticamente sul complemento della dimensione del set di test.
random_state: controlla la casualità applicata ai dati prima dell’applicazione della suddivisione. Passare un intero per una riproducibilità ripetibile.
shuffle: se True, i dati vengono mescolati prima della suddivisione.
stratify: se non è None, i dati vengono suddivisi in modo stratificato, utilizzando questo come etichette di classe.

In [13]:
from sklearn.model_selection import train_test_split

# X e Y sono nel blocco in alto

# trasposizione array
X_T = X.T

# Divisione per colonne
X_train_T, X_test_T = train_test_split(X_T, test_size=0.3)

# Divisione per righe di Y
#Y_train, Y_test = train_test_split(Y, test_size=0.3)                 # Non è necessario

# Ri-trasposizione dei risultati
X_train = X_train_T.T
X_test = X_test_T.T

print("Array originale:\n", X)
print("Array diviso per colonne:\n", X_train, "\n", X_test)
#print("Array originale:\n", Y)
#print("Array diviso per colonne:\n", Y_train, "\n", Y_test)


Array originale:
 [[0.1796053  0.1796053  0.26940795 ... 0.1796053  0.08980265 0.08980265]
 [0.18490007 0.18490007 0.2773501  ... 0.18490007 0.18490007 0.2773501 ]
 [0.1933473  0.1933473  0.1933473  ... 0.09667365 0.1933473  0.1933473 ]
 ...
 [0.07881104 0.07881104 0.07881104 ... 0.07881104 0.31524416 0.23643312]
 [0.14948702 0.07474351 0.14948702 ... 0.07474351 0.37371755 0.22423053]
 [0.07254763 0.07254763 0.07254763 ... 0.07254763 0.36273813 0.2901905 ]]
Array diviso per colonne:
 [[0.1796053  0.08980265 0.1796053  ... 0.26940795 0.1796053  0.1796053 ]
 [0.18490007 0.09245003 0.18490007 ... 0.18490007 0.18490007 0.18490007]
 [0.1933473  0.1933473  0.1933473  ... 0.1933473  0.1933473  0.1933473 ]
 ...
 [0.15762208 0.15762208 0.07881104 ... 0.15762208 0.15762208 0.15762208]
 [0.22423053 0.07474351 0.07474351 ... 0.14948702 0.07474351 0.07474351]
 [0.14509525 0.14509525 0.07254763 ... 0.21764288 0.14509525 0.07254763]] 
 [[0.1796053  0.1796053  0.26940795 ... 0.08980265 0.08980265 0.08

In [14]:
print(X_train.shape)
print(X_test.shape)
print(Y.shape)
#print(Y_train.shape)
#print(Y_test.shape)

(145, 21)
(145, 9)
(145, 1)


Per determinare le colonne più influenti, puoi utilizzare tecniche di selezione delle feature come l’analisi delle componenti principali (PCA) o la regressione Lasso 1. Queste tecniche possono aiutare a identificare le colonne che hanno il maggiore impatto sul modello.

In alternativa, puoi utilizzare la funzione f_regression di scikit-learn per calcolare il coefficiente di correlazione tra ogni colonna e il target 2. Questo ti darà un’idea di quali colonne sono più correlate al target e quindi potrebbero essere più influenti.

Ecco un esempio di come utilizzare f_regression per calcolare il coefficiente di correlazione tra ogni colonna e il target:

In [15]:
from sklearn.feature_selection import f_regression



# Calcolo del coefficiente di correlazione
f_values, p_values = f_regression(X, Y)

# Stampa dei risultati
for i in range(len(f_values)):
    print("Colonna", i+1, "- Coefficiente di correlazione:", f_values[i])


Colonna 1 - Coefficiente di correlazione: 3.1611706562365076
Colonna 2 - Coefficiente di correlazione: 11.363742833140254
Colonna 3 - Coefficiente di correlazione: 0.23814028998381798
Colonna 4 - Coefficiente di correlazione: 0.2579749468964486
Colonna 5 - Coefficiente di correlazione: 1.4665388531331744
Colonna 6 - Coefficiente di correlazione: 2.146959595012157
Colonna 7 - Coefficiente di correlazione: 1.4131211833355697
Colonna 8 - Coefficiente di correlazione: 5.787480123629315
Colonna 9 - Coefficiente di correlazione: 5.118973509978078
Colonna 10 - Coefficiente di correlazione: 0.01462118142480325
Colonna 11 - Coefficiente di correlazione: 0.22942176943683773
Colonna 12 - Coefficiente di correlazione: 0.11383677139420396
Colonna 13 - Coefficiente di correlazione: 0.24698334689505452
Colonna 14 - Coefficiente di correlazione: 0.08939849704267601
Colonna 15 - Coefficiente di correlazione: 0.89000996611988
Colonna 16 - Coefficiente di correlazione: 0.9490910907785033
Colonna 17 - Coe

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In questo esempio, l’array X rappresenta le colonne e l’array y rappresenta il target. La funzione f_regression viene quindi applicata all’array X per calcolare il coefficiente di correlazione tra ogni colonna e il target. Infine, i risultati vengono stampati a schermo.

Il coefficiente di correlazione è una misura statistica che esprime il grado di relazione lineare tra due variabili. Il coefficiente di correlazione varia da -1 a 1, dove -1 indica una correlazione negativa perfetta, 0 indica nessuna correlazione, e 1 indica una correlazione positiva perfetta .

In generale, i valori più alti del coefficiente di correlazione indicano una maggiore correlazione tra le colonne e il target. Questo significa che le colonne con valori più alti hanno un maggiore impatto sul target e quindi potrebbero essere più influenti. Tuttavia, bisogna fare attenzione a non confondere correlazione con causalità, in quanto una forte correlazione non implica necessariamente una relazione causale tra le variabili .